/* automatically generated with script */
#include "loader.hpp"
namespace LoadData
{
const struct syscall_entry bsd_syscall_table[] = {
		{1,	"exit",
	{"int_rval"}},
		{2,	"fork",
	{"void"}},
		{3,	"read",
	{"int_fd","_user_addr_t_cbuf","_user_size_t_nbyte"}},
		{4,	"write",
	{"int_fd","_user_addr_t_cbuf","_user_size_t_nbyte"}},
		{5,	"open",
	{"user_addr_t_path","_int_flags","_int_mode"}},
		{6,	"close",
	{"int_fd"}},
		{7,	"wait4",
	{"int_pid","_user_addr_t_status","_int_options","_user_addr_t_rusage"}},
		{9,	"link",
	{"user_addr_t_path","_user_addr_t_link"}},
		{10,	"unlink",
	{"user_addr_t_path"}},
		{12,	"chdir",
	{"user_addr_t_path"}},
		{13,	"fchdir",
	{"int_fd"}},
		{14,	"mknod",
	{"user_addr_t_path","_int_mode","_int_dev"}},
		{15,	"chmod",
	{"user_addr_t_path","_int_mode"}},
		{16,	"chown",
	{"user_addr_t_path","_int_uid","_int_gid"}},
		{18,	"getfsstat",
	{"user_addr_t_buf","_int_bufsize","_int_flags"}},
		{20,	"getpid",
	{"void"}},
		{23,	"setuid",
	{"uid_t_uid"}},
		{24,	"getuid",
	{"void"}},
		{25,	"geteuid",
	{"void"}},
		{26,	"ptrace",
	{"int_req","_pid_t_pid","_caddr_t_addr","_int_data"}},
		{27,	"recvmsg",
	{"int_s","_struct_msghdr_*msg","_int_flags"}},
		{28,	"sendmsg",
	{"int_s","_caddr_t_msg","_int_flags"}},
		{29,	"recvfrom",
	{"int_s","_void_*buf","_size_t_len","_int_flags","_struct_sockaddr_*from","_int_*fromlenaddr"}},
		{30,	"accept",
	{"int_s","_caddr_t_name","_socklen_t_*anamelen"}},
		{31,	"getpeername",
	{"int_fdes","_caddr_t_asa","_socklen_t_*alen"}},
		{32,	"getsockname",
	{"int_fdes","_caddr_t_asa","_socklen_t_*alen"}},
		{33,	"access",
	{"user_addr_t_path","_int_flags"}},
		{34,	"chflags",
	{"char_*path","_int_flags"}},
		{35,	"fchflags",
	{"int_fd","_int_flags"}},
		{36,	"sync",
	{"void"}},
		{37,	"kill",
	{"int_pid","_int_signum","_int_posix"}},
		{39,	"getppid",
	{"void"}},
		{41,	"dup",
	{"u_int_fd"}},
		{42,	"pipe",
	{"void"}},
		{43,	"getegid",
	{"void"}},
		{46,	"sigaction",
	{"int_signum","_struct___sigaction_*nsa","_struct_sigaction_*osa"}},
		{47,	"getgid",
	{"void"}},
		{48,	"sigprocmask",
	{"int_how","_user_addr_t_mask","_user_addr_t_omask"}},
		{49,	"getlogin",
	{"char_*namebuf","_u_int_namelen"}},
		{50,	"setlogin",
	{"char_*namebuf"}},
		{51,	"acct",
	{"char_*path"}},
		{52,	"sigpending",
	{"struct_sigvec_*osv"}},
		{53,	"sigaltstack",
	{"struct_sigaltstack_*nss","_struct_sigaltstack_*oss"}},
		{54,	"ioctl",
	{"int_fd","_u_long_com","_caddr_t_data"}},
		{55,	"reboot",
	{"int_opt","_char_*msg"}},
		{56,	"revoke",
	{"char_*path"}},
		{57,	"symlink",
	{"char_*path","_char_*link"}},
		{58,	"readlink",
	{"char_*path","_char_*buf","_int_count"}},
		{59,	"execve",
	{"char_*fname","_char_**argp","_char_**envp"}},
		{60,	"umask",
	{"int_newmask"}},
		{61,	"chroot",
	{"user_addr_t_path"}},
		{65,	"msync",
	{"caddr_t_addr","_size_t_len","_int_flags"}},
		{66,	"vfork",
	{"void"}},
		{73,	"munmap",
	{"caddr_t_addr","_size_t_len"}},
		{74,	"mprotect",
	{"caddr_t_addr","_size_t_len","_int_prot"}},
		{75,	"madvise",
	{"caddr_t_addr","_size_t_len","_int_behav"}},
		{78,	"mincore",
	{"user_addr_t_addr","_user_size_t_len","_user_addr_t_vec"}},
		{79,	"getgroups",
	{"u_int_gidsetsize","_gid_t_*gidset"}},
		{80,	"setgroups",
	{"u_int_gidsetsize","_gid_t_*gidset"}},
		{81,	"getpgrp",
	{"void"}},
		{82,	"setpgid",
	{"int_pid","_int_pgid"}},
		{83,	"setitimer",
	{"u_int_which","_struct_itimerval_*itv","_struct_itimerval_*oitv"}},
		{85,	"swapon",
	{"void"}},
		{86,	"getitimer",
	{"u_int_which","_struct_itimerval_*itv"}},
		{89,	"getdtablesize",
	{"void"}},
		{90,	"dup2",
	{"u_int_from","_u_int_to"}},
		{92,	"fcntl",
	{"int_fd","_int_cmd","_long_arg"}},
		{93,	"select",
	{"int_nd","_u_int32_t_*in","_u_int32_t_*ou","_u_int32_t_*ex","_struct_timeval_*tv"}},
		{95,	"fsync",
	{"int_fd"}},
		{96,	"setpriority",
	{"int_which","_id_t_who","_int_prio"}},
		{97,	"socket",
	{"int_domain","_int_type","_int_protocol"}},
		{98,	"connect",
	{"int_s","_caddr_t_name","_socklen_t_namelen"}},
		{100,	"getpriority",
	{"int_which","_id_t_who"}},
		{104,	"bind",
	{"int_s","_caddr_t_name","_socklen_t_namelen"}},
		{105,	"setsockopt",
	{"int_s","_int_level","_int_name","_caddr_t_val","_socklen_t_valsize"}},
		{106,	"listen",
	{"int_s","_int_backlog"}},
		{111,	"sigsuspend",
	{"sigset_t_mask"}},
		{116,	"gettimeofday",
	{"struct_timeval_*tp","_struct_timezone_*tzp","_uint64_t_*mach_absolute_time"}},
		{117,	"getrusage",
	{"int_who","_struct_rusage_*rusage"}},
		{118,	"getsockopt",
	{"int_s","_int_level","_int_name","_caddr_t_val","_socklen_t_*avalsize"}},
		{120,	"readv",
	{"int_fd","_struct_iovec_*iovp","_u_int_iovcnt"}},
		{121,	"writev",
	{"int_fd","_struct_iovec_*iovp","_u_int_iovcnt"}},
		{122,	"settimeofday",
	{"struct_timeval_*tv","_struct_timezone_*tzp"}},
		{123,	"fchown",
	{"int_fd","_int_uid","_int_gid"}},
		{124,	"fchmod",
	{"int_fd","_int_mode"}},
		{126,	"setreuid",
	{"uid_t_ruid","_uid_t_euid"}},
		{127,	"setregid",
	{"gid_t_rgid","_gid_t_egid"}},
		{128,	"rename",
	{"char_*from","_char_*to"}},
		{131,	"flock",
	{"int_fd","_int_how"}},
		{132,	"mkfifo",
	{"user_addr_t_path","_int_mode"}},
		{133,	"sendto",
	{"int_s","_caddr_t_buf","_size_t_len","_int_flags","_caddr_t_to","_socklen_t_tolen"}},
		{134,	"shutdown",
	{"int_s","_int_how"}},
		{135,	"socketpair",
	{"int_domain","_int_type","_int_protocol","_int_*rsv"}},
		{136,	"mkdir",
	{"user_addr_t_path","_int_mode"}},
		{137,	"rmdir",
	{"char_*path"}},
		{138,	"utimes",
	{"char_*path","_struct_timeval_*tptr"}},
		{139,	"futimes",
	{"int_fd","_struct_timeval_*tptr"}},
		{140,	"adjtime",
	{"struct_timeval_*delta","_struct_timeval_*olddelta"}},
		{142,	"gethostuuid",
	{"unsigned_char_*uuid_buf","_const_struct_timespec_*timeoutp","_int_spi"}},
		{147,	"setsid",
	{"void"}},
		{151,	"getpgid",
	{"pid_t_pid"}},
		{152,	"setprivexec",
	{"int_flag"}},
		{153,	"pread",
	{"int_fd","_user_addr_t_buf","_user_size_t_nbyte","_off_t_offset"}},
		{154,	"pwrite",
	{"int_fd","_user_addr_t_buf","_user_size_t_nbyte","_off_t_offset"}},
		{155,	"nfssvc",
	{"int_flag","_caddr_t_argp"}},
		{157,	"statfs",
	{"char_*path","_struct_statfs_*buf"}},
		{158,	"fstatfs",
	{"int_fd","_struct_statfs_*buf"}},
		{159,	"unmount",
	{"user_addr_t_path","_int_flags"}},
		{161,	"getfh",
	{"char_*fname","_fhandle_t_*fhp"}},
		{165,	"quotactl",
	{"const_char_*path","_int_cmd","_int_uid","_caddr_t_arg"}},
		{167,	"mount",
	{"char_*type","_char_*path","_int_flags","_caddr_t_data"}},
		{169,	"csops",
	{"pid_t_pid","_uint32_t_ops","_user_addr_t_useraddr","_user_size_t_usersize"}},
		{170,	"csops_audittoken",
	{"pid_t_pid","_uint32_t_ops","_user_addr_t_useraddr","_user_size_t_usersize","_user_addr_t_uaudittoken"}},
		{173,	"waitid",
	{"idtype_t_idtype","_id_t_id","_siginfo_t_*infop","_int_options"}},
		{177,	"kdebug_typefilter",
	{"void**_addr","_size_t*_size"}},
		{178,	"kdebug_trace_string",
	{"uint32_t_debugid","_uint64_t_str_id","_const_char_*str"}},
		{179,	"kdebug_trace64",
	{"uint32_t_code","_uint64_t_arg1","_uint64_t_arg2","_uint64_t_arg3","_uint64_t_arg4"}},
		{180,	"kdebug_trace",
	{"uint32_t_code","_u_long_arg1","_u_long_arg2","_u_long_arg3","_u_long_arg4"}},
		{181,	"setgid",
	{"gid_t_gid"}},
		{182,	"setegid",
	{"gid_t_egid"}},
		{183,	"seteuid",
	{"uid_t_euid"}},
		{184,	"sigreturn",
	{"struct_ucontext_*uctx","_int_infostyle","_user_addr_t_token"}},
		{186,	"thread_selfcounts",
	{"int_type","_user_addr_t_buf","_user_size_t_nbytes"}},
		{187,	"fdatasync",
	{"int_fd"}},
		{188,	"stat",
	{"user_addr_t_path","_user_addr_t_ub"}},
		{189,	"fstat",
	{"int_fd","_user_addr_t_ub"}},
		{190,	"lstat",
	{"user_addr_t_path","_user_addr_t_ub"}},
		{191,	"pathconf",
	{"char_*path","_int_name"}},
		{192,	"fpathconf",
	{"int_fd","_int_name"}},
		{194,	"getrlimit",
	{"u_int_which","_struct_rlimit_*rlp"}},
		{195,	"setrlimit",
	{"u_int_which","_struct_rlimit_*rlp"}},
		{196,	"getdirentries",
	{"int_fd","_char_*buf","_u_int_count","_long_*basep"}},
		{197,	"mmap",
	{"caddr_t_addr","_size_t_len","_int_prot","_int_flags","_int_fd","_off_t_pos"}},
		{199,	"lseek",
	{"int_fd","_off_t_offset","_int_whence"}},
		{200,	"truncate",
	{"char_*path","_off_t_length"}},
		{201,	"ftruncate",
	{"int_fd","_off_t_length"}},
		{202,	"sysctl",
	{"int_*name","_u_int_namelen","_void_*old","_size_t_*oldlenp","_void_*new","_size_t_newlen"}},
		{203,	"mlock",
	{"caddr_t_addr","_size_t_len"}},
		{204,	"munlock",
	{"caddr_t_addr","_size_t_len"}},
		{205,	"undelete",
	{"user_addr_t_path"}},
		{216,	"open_dprotected_np",
	{"user_addr_t_path","_int_flags","_int_class","_int_dpflags","_int_mode"}},
		{220,	"getattrlist",
	{"const_char_*path","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_u_long_options"}},
		{221,	"setattrlist",
	{"const_char_*path","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_u_long_options"}},
		{222,	"getdirentriesattr",
	{"int_fd","_struct_attrlist_*alist","_void_*buffer","_size_t_buffersize","_u_long_*count","_u_long_*basep","_u_long_*newstate","_u_long_options"}},
		{223,	"exchangedata",
	{"const_char_*path1","_const_char_*path2","_u_long_options"}},
		{225,	"searchfs",
	{"const_char_*path","_struct_fssearchblock_*searchblock","_uint32_t_*nummatches","_uint32_t_scriptcode","_uint32_t_options","_struct_searchstate_*state"}},
		{226,	"delete",
	{"user_addr_t_path"}},
		{227,	"copyfile",
	{"char_*from","_char_*to","_int_mode","_int_flags"}},
		{228,	"fgetattrlist",
	{"int_fd","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_u_long_options"}},
		{229,	"fsetattrlist",
	{"int_fd","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_u_long_options"}},
		{230,	"poll",
	{"struct_pollfd_*fds","_u_int_nfds","_int_timeout"}},
		{231,	"watchevent",
	{"struct_eventreq_*u_req","_int_u_eventmask"}},
		{232,	"waitevent",
	{"struct_eventreq_*u_req","_struct_timeval_*tv"}},
		{233,	"modwatch",
	{"struct_eventreq_*u_req","_int_u_eventmask"}},
		{234,	"getxattr",
	{"user_addr_t_path","_user_addr_t_attrname","_user_addr_t_value","_size_t_size","_uint32_t_position","_int_options"}},
		{235,	"fgetxattr",
	{"int_fd","_user_addr_t_attrname","_user_addr_t_value","_size_t_size","_uint32_t_position","_int_options"}},
		{236,	"setxattr",
	{"user_addr_t_path","_user_addr_t_attrname","_user_addr_t_value","_size_t_size","_uint32_t_position","_int_options"}},
		{237,	"fsetxattr",
	{"int_fd","_user_addr_t_attrname","_user_addr_t_value","_size_t_size","_uint32_t_position","_int_options"}},
		{238,	"removexattr",
	{"user_addr_t_path","_user_addr_t_attrname","_int_options"}},
		{239,	"fremovexattr",
	{"int_fd","_user_addr_t_attrname","_int_options"}},
		{240,	"listxattr",
	{"user_addr_t_path","_user_addr_t_namebuf","_size_t_bufsize","_int_options"}},
		{241,	"flistxattr",
	{"int_fd","_user_addr_t_namebuf","_size_t_bufsize","_int_options"}},
		{242,	"fsctl",
	{"const_char_*path","_u_long_cmd","_caddr_t_data","_u_int_options"}},
		{243,	"initgroups",
	{"u_int_gidsetsize","_gid_t_*gidset","_int_gmuid"}},
		{244,	"posix_spawn",
	{"pid_t_*pid","_const_char_*path","_const_struct__posix_spawn_args_desc_*adesc","_char_**argv","_char_**envp"}},
		{245,	"ffsctl",
	{"int_fd","_u_long_cmd","_caddr_t_data","_u_int_options"}},
		{247,	"nfsclnt",
	{"int_flag","_caddr_t_argp"}},
		{248,	"fhopen",
	{"const_struct_fhandle_*u_fhp","_int_flags"}},
		{250,	"minherit",
	{"void_*addr","_size_t_len","_int_inherit"}},
		{251,	"semsys",
	{"u_int_which","_int_a2","_int_a3","_int_a4","_int_a5"}},
		{252,	"msgsys",
	{"u_int_which","_int_a2","_int_a3","_int_a4","_int_a5"}},
		{253,	"shmsys",
	{"u_int_which","_int_a2","_int_a3","_int_a4"}},
		{254,	"semctl",
	{"int_semid","_int_semnum","_int_cmd","_semun_t_arg"}},
		{255,	"semget",
	{"key_t_key","_int_nsems","_int_semflg"}},
		{256,	"semop",
	{"int_semid","_struct_sembuf_*sops","_int_nsops"}},
		{258,	"msgctl",
	{"int_msqid","_int_cmd","_struct_msqid_ds_*buf"}},
		{259,	"msgget",
	{"key_t_key","_int_msgflg"}},
		{260,	"msgsnd",
	{"int_msqid","_void_*msgp","_size_t_msgsz","_int_msgflg"}},
		{261,	"msgrcv",
	{"int_msqid","_void_*msgp","_size_t_msgsz","_long_msgtyp","_int_msgflg"}},
		{262,	"shmat",
	{"int_shmid","_void_*shmaddr","_int_shmflg"}},
		{263,	"shmctl",
	{"int_shmid","_int_cmd","_struct_shmid_ds_*buf"}},
		{264,	"shmdt",
	{"void_*shmaddr"}},
		{265,	"shmget",
	{"key_t_key","_size_t_size","_int_shmflg"}},
		{266,	"shm_open",
	{"const_char_*name","_int_oflag","_int_mode"}},
		{267,	"shm_unlink",
	{"const_char_*name"}},
		{268,	"sem_open",
	{"const_char_*name","_int_oflag","_int_mode","_int_value"}},
		{269,	"sem_close",
	{"sem_t_*sem"}},
		{270,	"sem_unlink",
	{"const_char_*name"}},
		{271,	"sem_wait",
	{"sem_t_*sem"}},
		{272,	"sem_trywait",
	{"sem_t_*sem"}},
		{273,	"sem_post",
	{"sem_t_*sem"}},
		{274,	"sysctlbyname",
	{"const_char_*name","_size_t_namelen","_void_*old","_size_t_*oldlenp","_void_*new","_size_t_newlen"}},
		{277,	"open_extended",
	{"user_addr_t_path","_int_flags","_uid_t_uid","_gid_t_gid","_int_mode","_user_addr_t_xsecurity"}},
		{278,	"umask_extended",
	{"int_newmask","_user_addr_t_xsecurity"}},
		{279,	"stat_extended",
	{"user_addr_t_path","_user_addr_t_ub","_user_addr_t_xsecurity","_user_addr_t_xsecurity_size"}},
		{280,	"lstat_extended",
	{"user_addr_t_path","_user_addr_t_ub","_user_addr_t_xsecurity","_user_addr_t_xsecurity_size"}},
		{281,	"fstat_extended",
	{"int_fd","_user_addr_t_ub","_user_addr_t_xsecurity","_user_addr_t_xsecurity_size"}},
		{282,	"chmod_extended",
	{"user_addr_t_path","_uid_t_uid","_gid_t_gid","_int_mode","_user_addr_t_xsecurity"}},
		{283,	"fchmod_extended",
	{"int_fd","_uid_t_uid","_gid_t_gid","_int_mode","_user_addr_t_xsecurity"}},
		{284,	"access_extended",
	{"user_addr_t_entries","_size_t_size","_user_addr_t_results","_uid_t_uid"}},
		{285,	"settid",
	{"uid_t_uid","_gid_t_gid"}},
		{286,	"gettid",
	{"uid_t_*uidp","_gid_t_*gidp"}},
		{287,	"setsgroups",
	{"int_setlen","_user_addr_t_guidset"}},
		{288,	"getsgroups",
	{"user_addr_t_setlen","_user_addr_t_guidset"}},
		{289,	"setwgroups",
	{"int_setlen","_user_addr_t_guidset"}},
		{290,	"getwgroups",
	{"user_addr_t_setlen","_user_addr_t_guidset"}},
		{291,	"mkfifo_extended",
	{"user_addr_t_path","_uid_t_uid","_gid_t_gid","_int_mode","_user_addr_t_xsecurity"}},
		{292,	"mkdir_extended",
	{"user_addr_t_path","_uid_t_uid","_gid_t_gid","_int_mode","_user_addr_t_xsecurity"}},
		{293,	"identitysvc",
	{"int_opcode","_user_addr_t_message"}},
		{294,	"shared_region_check_np",
	{"uint64_t_*start_address"}},
		{296,	"vm_pressure_monitor",
	{"int_wait_for_pressure","_int_nsecs_monitored","_uint32_t_*pages_reclaimed"}},
		{297,	"psynch_rw_longrdlock",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{298,	"psynch_rw_yieldwrlock",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{299,	"psynch_rw_downgrade",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{300,	"psynch_rw_upgrade",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{301,	"psynch_mutexwait",
	{"user_addr_t_mutex","__uint32_t_mgen","_uint32_t__ugen","_uint64_t_tid","_uint32_t_flags"}},
		{302,	"psynch_mutexdrop",
	{"user_addr_t_mutex","__uint32_t_mgen","_uint32_t__ugen","_uint64_t_tid","_uint32_t_flags"}},
		{303,	"psynch_cvbroad",
	{"user_addr_t_cv","_uint64_t_cvlsgen","_uint64_t_cvudgen","_uint32_t_flags","_user_addr_t_mutex","__uint64_t_mugen","_uint64_t_tid"}},
		{304,	"psynch_cvsignal",
	{"user_addr_t_cv","_uint64_t_cvlsgen","_uint32_t_cvugen","_int_thread_port","_user_addr_t_mutex","__uint64_t_mugen","_uint64_t_tid","_uint32_t_flags"}},
		{305,	"psynch_cvwait",
	{"user_addr_t_cv","_uint64_t_cvlsgen","_uint32_t_cvugen","_user_addr_t_mutex","__uint64_t_mugen","_uint32_t_flags","_int64_t_sec","_uint32_t_nsec"}},
		{306,	"psynch_rw_rdlock",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{307,	"psynch_rw_wrlock",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{308,	"psynch_rw_unlock",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{309,	"psynch_rw_unlock2",
	{"user_addr_t_rwlock","_uint32_t_lgenval","_uint32_t_ugenval","_uint32_t_rw_wc","_int_flags"}},
		{310,	"getsid",
	{"pid_t_pid"}},
		{311,	"settid_with_pid",
	{"pid_t_pid","_int_assume"}},
		{312,	"psynch_cvclrprepost",
	{"user_addr_t_cv","_uint32_t_cvgen","_uint32_t_cvugen","_uint32_t_cvsgen","_uint32_t_prepocnt","_uint32_t_preposeq","_uint32_t_flags"}},
		{313,	"aio_fsync",
	{"int_op","_user_addr_t_aiocbp"}},
		{314,	"aio_return",
	{"user_addr_t_aiocbp"}},
		{315,	"aio_suspend",
	{"user_addr_t_aiocblist","_int_nent","_user_addr_t_timeoutp"}},
		{316,	"aio_cancel",
	{"int_fd","_user_addr_t_aiocbp"}},
		{317,	"aio_error",
	{"user_addr_t_aiocbp"}},
		{318,	"aio_read",
	{"user_addr_t_aiocbp"}},
		{319,	"aio_write",
	{"user_addr_t_aiocbp"}},
		{320,	"lio_listio",
	{"int_mode","_user_addr_t_aiocblist","_int_nent","_user_addr_t_sigp"}},
		{322,	"iopolicysys",
	{"int_cmd","_void_*arg"}},
		{323,	"process_policy",
	{"int_scope","_int_action","_int_policy","_int_policy_subtype","_user_addr_t_attrp","_pid_t_target_pid","_uint64_t_target_threadid"}},
		{324,	"mlockall",
	{"int_how"}},
		{325,	"munlockall",
	{"int_how"}},
		{327,	"issetugid",
	{"void"}},
		{328,	"pthread_kill",
	{"int_thread_port","_int_sig"}},
		{329,	"pthread_sigmask",
	{"int_how","_user_addr_t_set","_user_addr_t_oset"}},
		{330,	"sigwait",
	{"user_addr_t_set","_user_addr_t_sig"}},
		{331,	"disable_threadsignal",
	{"int_value"}},
		{332,	"pthread_markcancel",
	{"int_thread_port"}},
		{333,	"pthread_canceled",
	{"int__action"}},
		{334,	"semwait_signal",
	{"int_cond_sem","_int_mutex_sem","_int_timeout","_int_relative","_int64_t_tv_sec","_int32_t_tv_nsec"}},
		{336,	"proc_info",
	{"int32_t_callnum","int32_t_pid","uint32_t_flavor","_uint64_t_arg","user_addr_t_buffer","int32_t_buffersize"}},
		{337,	"sendfile",
	{"int_fd","_int_s","_off_t_offset","_off_t_*nbytes","_struct_sf_hdtr_*hdtr","_int_flags"}},
		{338,	"stat64",
	{"user_addr_t_path","_user_addr_t_ub"}},
		{339,	"fstat64",
	{"int_fd","_user_addr_t_ub"}},
		{340,	"lstat64",
	{"user_addr_t_path","_user_addr_t_ub"}},
		{341,	"stat64_extended",
	{"user_addr_t_path","_user_addr_t_ub","_user_addr_t_xsecurity","_user_addr_t_xsecurity_size"}},
		{342,	"lstat64_extended",
	{"user_addr_t_path","_user_addr_t_ub","_user_addr_t_xsecurity","_user_addr_t_xsecurity_size"}},
		{343,	"fstat64_extended",
	{"int_fd","_user_addr_t_ub","_user_addr_t_xsecurity","_user_addr_t_xsecurity_size"}},
		{344,	"getdirentries64",
	{"int_fd","_void_*buf","_user_size_t_bufsize","_off_t_*position"}},
		{345,	"statfs64",
	{"char_*path","_struct_statfs64_*buf"}},
		{346,	"fstatfs64",
	{"int_fd","_struct_statfs64_*buf"}},
		{347,	"getfsstat64",
	{"user_addr_t_buf","_int_bufsize","_int_flags"}},
		{348,	"pthread_chdir",
	{"user_addr_t_path"}},
		{349,	"pthread_fchdir",
	{"int_fd"}},
		{350,	"audit",
	{"void_*record","_int_length"}},
		{351,	"auditon",
	{"int_cmd","_void_*data","_int_length"}},
		{353,	"getauid",
	{"au_id_t_*auid"}},
		{354,	"setauid",
	{"au_id_t_*auid"}},
		{357,	"getaudit_addr",
	{"struct_auditinfo_addr_*auditinfo_addr","_int_length"}},
		{358,	"setaudit_addr",
	{"struct_auditinfo_addr_*auditinfo_addr","_int_length"}},
		{359,	"auditctl",
	{"char_*path"}},
		{360,	"bsdthread_create",
	{"user_addr_t_func","_user_addr_t_func_arg","_user_addr_t_stack","_user_addr_t_pthread","_uint32_t_flags"}},
		{361,	"bsdthread_terminate",
	{"user_addr_t_stackaddr","_size_t_freesize","_uint32_t_port","_uint32_t_sem"}},
		{362,	"kqueue",
	{"void"}},
		{363,	"kevent",
	{"int_fd","_const_struct_kevent_*changelist","_int_nchanges","_struct_kevent_*eventlist","_int_nevents","_const_struct_timespec_*timeout"}},
		{364,	"lchown",
	{"user_addr_t_path","_uid_t_owner","_gid_t_group"}},
		{366,	"bsdthread_register",
	{"user_addr_t_threadstart","_user_addr_t_wqthread","_uint32_t_flags","_user_addr_t_stack_addr_hint","_user_addr_t_targetconc_ptr","_uint32_t_dispatchqueue_offset","_uint32_t_tsd_offset"}},
		{367,	"workq_open",
	{"void"}},
		{368,	"workq_kernreturn",
	{"int_options","_user_addr_t_item","_int_affinity","_int_prio"}},
		{369,	"kevent64",
	{"int_fd","_const_struct_kevent64_s_*changelist","_int_nchanges","_struct_kevent64_s_*eventlist","_int_nevents","_unsigned_int_flags","_const_struct_timespec_*timeout"}},
		{370,	"old_semwait_signal",
	{"int_cond_sem","_int_mutex_sem","_int_timeout","_int_relative","_const_struct_timespec_*ts"}},
		{371,	"old_semwait_signal_nocancel",
	{"int_cond_sem","_int_mutex_sem","_int_timeout","_int_relative","_const_struct_timespec_*ts"}},
		{372,	"thread_selfid",
	{"void"}},
		{373,	"ledger",
	{"int_cmd","_caddr_t_arg1","_caddr_t_arg2","_caddr_t_arg3"}},
		{374,	"kevent_qos",
	{"int_fd","_const_struct_kevent_qos_s_*changelist","_int_nchanges","_struct_kevent_qos_s_*eventlist","_int_nevents","_void_*data_out","_size_t_*data_available","_unsigned_int_flags"}},
		{375,	"kevent_id",
	{"uint64_t_id","_const_struct_kevent_qos_s_*changelist","_int_nchanges","_struct_kevent_qos_s_*eventlist","_int_nevents","_void_*data_out","_size_t_*data_available","_unsigned_int_flags"}},
		{380,	"mac_execve",
	{"char_*fname","_char_**argp","_char_**envp","_struct_mac_*mac_p"}},
		{381,	"mac_syscall",
	{"char_*policy","_int_call","_user_addr_t_arg"}},
		{382,	"mac_get_file",
	{"char_*path_p","_struct_mac_*mac_p"}},
		{383,	"mac_set_file",
	{"char_*path_p","_struct_mac_*mac_p"}},
		{384,	"mac_get_link",
	{"char_*path_p","_struct_mac_*mac_p"}},
		{385,	"mac_set_link",
	{"char_*path_p","_struct_mac_*mac_p"}},
		{386,	"mac_get_proc",
	{"struct_mac_*mac_p"}},
		{387,	"mac_set_proc",
	{"struct_mac_*mac_p"}},
		{388,	"mac_get_fd",
	{"int_fd","_struct_mac_*mac_p"}},
		{389,	"mac_set_fd",
	{"int_fd","_struct_mac_*mac_p"}},
		{390,	"mac_get_pid",
	{"pid_t_pid","_struct_mac_*mac_p"}},
		{394,	"pselect",
	{"int_nd","_u_int32_t_*in","_u_int32_t_*ou","_u_int32_t_*ex","_const_struct_timespec_*ts","_const_struct_sigset_t_*mask"}},
		{395,	"pselect_nocancel",
	{"int_nd","_u_int32_t_*in","_u_int32_t_*ou","_u_int32_t_*ex","_const_struct_timespec_*ts","_const_struct_sigset_t_*mask"}},
		{396,	"read_nocancel",
	{"int_fd","_user_addr_t_cbuf","_user_size_t_nbyte"}},
		{397,	"write_nocancel",
	{"int_fd","_user_addr_t_cbuf","_user_size_t_nbyte"}},
		{398,	"open_nocancel",
	{"user_addr_t_path","_int_flags","_int_mode"}},
		{399,	"close_nocancel",
	{"int_fd"}},
		{400,	"wait4_nocancel",
	{"int_pid","_user_addr_t_status","_int_options","_user_addr_t_rusage"}},
		{401,	"recvmsg_nocancel",
	{"int_s","_struct_msghdr_*msg","_int_flags"}},
		{402,	"sendmsg_nocancel",
	{"int_s","_caddr_t_msg","_int_flags"}},
		{403,	"recvfrom_nocancel",
	{"int_s","_void_*buf","_size_t_len","_int_flags","_struct_sockaddr_*from","_int_*fromlenaddr"}},
		{404,	"accept_nocancel",
	{"int_s","_caddr_t_name","_socklen_t_*anamelen"}},
		{405,	"msync_nocancel",
	{"caddr_t_addr","_size_t_len","_int_flags"}},
		{406,	"fcntl_nocancel",
	{"int_fd","_int_cmd","_long_arg"}},
		{407,	"select_nocancel",
	{"int_nd","_u_int32_t_*in","_u_int32_t_*ou","_u_int32_t_*ex","_struct_timeval_*tv"}},
		{408,	"fsync_nocancel",
	{"int_fd"}},
		{409,	"connect_nocancel",
	{"int_s","_caddr_t_name","_socklen_t_namelen"}},
		{410,	"sigsuspend_nocancel",
	{"sigset_t_mask"}},
		{411,	"readv_nocancel",
	{"int_fd","_struct_iovec_*iovp","_u_int_iovcnt"}},
		{412,	"writev_nocancel",
	{"int_fd","_struct_iovec_*iovp","_u_int_iovcnt"}},
		{413,	"sendto_nocancel",
	{"int_s","_caddr_t_buf","_size_t_len","_int_flags","_caddr_t_to","_socklen_t_tolen"}},
		{414,	"pread_nocancel",
	{"int_fd","_user_addr_t_buf","_user_size_t_nbyte","_off_t_offset"}},
		{415,	"pwrite_nocancel",
	{"int_fd","_user_addr_t_buf","_user_size_t_nbyte","_off_t_offset"}},
		{416,	"waitid_nocancel",
	{"idtype_t_idtype","_id_t_id","_siginfo_t_*infop","_int_options"}},
		{417,	"poll_nocancel",
	{"struct_pollfd_*fds","_u_int_nfds","_int_timeout"}},
		{418,	"msgsnd_nocancel",
	{"int_msqid","_void_*msgp","_size_t_msgsz","_int_msgflg"}},
		{419,	"msgrcv_nocancel",
	{"int_msqid","_void_*msgp","_size_t_msgsz","_long_msgtyp","_int_msgflg"}},
		{420,	"sem_wait_nocancel",
	{"sem_t_*sem"}},
		{421,	"aio_suspend_nocancel",
	{"user_addr_t_aiocblist","_int_nent","_user_addr_t_timeoutp"}},
		{422,	"sigwait_nocancel",
	{"user_addr_t_set","_user_addr_t_sig"}},
		{423,	"semwait_signal_nocancel",
	{"int_cond_sem","_int_mutex_sem","_int_timeout","_int_relative","_int64_t_tv_sec","_int32_t_tv_nsec"}},
		{424,	"mac_mount",
	{"char_*type","_char_*path","_int_flags","_caddr_t_data","_struct_mac_*mac_p"}},
		{425,	"mac_get_mount",
	{"char_*path","_struct_mac_*mac_p"}},
		{426,	"mac_getfsstat",
	{"user_addr_t_buf","_int_bufsize","_user_addr_t_mac","_int_macsize","_int_flags"}},
		{427,	"fsgetpath",
	{"user_addr_t_buf","_size_t_bufsize","_user_addr_t_fsid","_uint64_t_objid"}},
		{428,	"audit_session_self",
	{"void"}},
		{429,	"audit_session_join",
	{"mach_port_name_t_port"}},
		{430,	"fileport_makeport",
	{"int_fd","_user_addr_t_portnamep"}},
		{431,	"fileport_makefd",
	{"mach_port_name_t_port"}},
		{432,	"audit_session_port",
	{"au_asid_t_asid","_user_addr_t_portnamep"}},
		{433,	"pid_suspend",
	{"int_pid"}},
		{434,	"pid_resume",
	{"int_pid"}},
		{435,	"pid_hibernate",
	{"int_pid"}},
		{436,	"pid_shutdown_sockets",
	{"int_pid","_int_level"}},
		{438,	"shared_region_map_and_slide_np",
	{"int_fd","_uint32_t_count","_const_struct_shared_file_mapping_np_*mappings","_uint32_t_slide","_uint64_t*_slide_start","_uint32_t_slide_size"}},
		{439,	"kas_info",
	{"int_selector","_void_*value","_size_t_*size"}},
		{440,	"memorystatus_control",
	{"uint32_t_command","_int32_t_pid","_uint32_t_flags","_user_addr_t_buffer","_size_t_buffersize"}},
		{441,	"guarded_open_np",
	{"user_addr_t_path","_const_guardid_t_*guard","_u_int_guardflags","_int_flags","_int_mode"}},
		{442,	"guarded_close_np",
	{"int_fd","_const_guardid_t_*guard"}},
		{443,	"guarded_kqueue_np",
	{"const_guardid_t_*guard","_u_int_guardflags"}},
		{444,	"change_fdguard_np",
	{"int_fd","_const_guardid_t_*guard","_u_int_guardflags","_const_guardid_t_*nguard","_u_int_nguardflags","_int_*fdflagsp"}},
		{445,	"usrctl",
	{"uint32_t_flags"}},
		{446,	"proc_rlimit_control",
	{"pid_t_pid","_int_flavor","_void_*arg"}},
		{447,	"connectx",
	{"int_socket","_const_sa_endpoints_t_*endpoints","_sae_associd_t_associd","_unsigned_int_flags","_const_struct_iovec_*iov","_unsigned_int_iovcnt","_size_t_*len","_sae_connid_t_*connid"}},
		{448,	"disconnectx",
	{"int_s","_sae_associd_t_aid","_sae_connid_t_cid"}},
		{449,	"peeloff",
	{"int_s","_sae_associd_t_aid"}},
		{450,	"socket_delegate",
	{"int_domain","_int_type","_int_protocol","_pid_t_epid"}},
		{451,	"telemetry",
	{"uint64_t_cmd","_uint64_t_deadline","_uint64_t_interval","_uint64_t_leeway","_uint64_t_arg4","_uint64_t_arg5"}},
		{452,	"proc_uuid_policy",
	{"uint32_t_operation","_uuid_t_uuid","_size_t_uuidlen","_uint32_t_flags"}},
		{453,	"memorystatus_get_level",
	{"user_addr_t_level"}},
		{454,	"system_override",
	{"uint64_t_timeout","_uint64_t_flags"}},
		{455,	"vfs_purge",
	{"void"}},
		{456,	"sfi_ctl",
	{"uint32_t_operation","_uint32_t_sfi_class","_uint64_t_time","_uint64_t_*out_time"}},
		{457,	"sfi_pidctl",
	{"uint32_t_operation","_pid_t_pid","_uint32_t_sfi_flags","_uint32_t_*out_sfi_flags"}},
		{458,	"coalition",
	{"uint32_t_operation","_uint64_t_*cid","_uint32_t_flags"}},
		{459,	"coalition_info",
	{"uint32_t_flavor","_uint64_t_*cid","_void_*buffer","_size_t_*bufsize"}},
		{460,	"necp_match_policy",
	{"uint8_t_*parameters","_size_t_parameters_size","_struct_necp_aggregate_result_*returned_result"}},
		{461,	"getattrlistbulk",
	{"int_dirfd","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_uint64_t_options"}},
		{462,	"clonefileat",
	{"int_src_dirfd","_user_addr_t_src","_int_dst_dirfd","_user_addr_t_dst","_uint32_t_flags"}},
		{463,	"openat",
	{"int_fd","_user_addr_t_path","_int_flags","_int_mode"}},
		{464,	"openat_nocancel",
	{"int_fd","_user_addr_t_path","_int_flags","_int_mode"}},
		{465,	"renameat",
	{"int_fromfd","_char_*from","_int_tofd","_char_*to"}},
		{466,	"faccessat",
	{"int_fd","_user_addr_t_path","_int_amode","_int_flag"}},
		{467,	"fchmodat",
	{"int_fd","_user_addr_t_path","_int_mode","_int_flag"}},
		{468,	"fchownat",
	{"int_fd","_user_addr_t_path","_uid_t_uid","gid_t_gid","_int_flag"}},
		{469,	"fstatat",
	{"int_fd","_user_addr_t_path","_user_addr_t_ub","_int_flag"}},
		{470,	"fstatat64",
	{"int_fd","_user_addr_t_path","_user_addr_t_ub","_int_flag"}},
		{471,	"linkat",
	{"int_fd1","_user_addr_t_path","_int_fd2","_user_addr_t_link","_int_flag"}},
		{472,	"unlinkat",
	{"int_fd","_user_addr_t_path","_int_flag"}},
		{473,	"readlinkat",
	{"int_fd","_user_addr_t_path","_user_addr_t_buf","_size_t_bufsize"}},
		{474,	"symlinkat",
	{"user_addr_t_*path1","_int_fd","_user_addr_t_path2"}},
		{475,	"mkdirat",
	{"int_fd","_user_addr_t_path","_int_mode"}},
		{476,	"getattrlistat",
	{"int_fd","_const_char_*path","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_u_long_options"}},
		{477,	"proc_trace_log",
	{"pid_t_pid","_uint64_t_uniqueid"}},
		{478,	"bsdthread_ctl",
	{"user_addr_t_cmd","_user_addr_t_arg1","_user_addr_t_arg2","_user_addr_t_arg3"}},
		{479,	"openbyid_np",
	{"user_addr_t_fsid","_user_addr_t_objid","_int_oflags"}},
		{480,	"recvmsg_x",
	{"int_s","_struct_msghdr_x_*msgp","_u_int_cnt","_int_flags"}},
		{481,	"sendmsg_x",
	{"int_s","_struct_msghdr_x_*msgp","_u_int_cnt","_int_flags"}},
		{482,	"thread_selfusage",
	{"void"}},
		{483,	"csrctl",
	{"uint32_t_op","_user_addr_t_useraddr","_user_addr_t_usersize"}},
		{484,	"guarded_open_dprotected_np",
	{"user_addr_t_path","_const_guardid_t_*guard","_u_int_guardflags","_int_flags","_int_dpclass","_int_dpflags","_int_mode"}},
		{485,	"guarded_write_np",
	{"int_fd","_const_guardid_t_*guard","_user_addr_t_cbuf","_user_size_t_nbyte"}},
		{486,	"guarded_pwrite_np",
	{"int_fd","_const_guardid_t_*guard","_user_addr_t_buf","_user_size_t_nbyte","_off_t_offset"}},
		{487,	"guarded_writev_np",
	{"int_fd","_const_guardid_t_*guard","_struct_iovec_*iovp","_int_iovcnt"}},
		{488,	"renameatx_np",
	{"int_fromfd","_char_*from","_int_tofd","_char_*to","_u_int_flags"}},
		{489,	"mremap_encrypted",
	{"caddr_t_addr","_size_t_len","_uint32_t_cryptid","_uint32_t_cputype","_uint32_t_cpusubtype"}},
		{490,	"netagent_trigger",
	{"uuid_t_agent_uuid","_size_t_agent_uuidlen"}},
		{491,	"stack_snapshot_with_config",
	{"int_stackshot_config_version","_user_addr_t_stackshot_config","_size_t_stackshot_config_size"}},
		{492,	"microstackshot",
	{"user_addr_t_tracebuf","_uint32_t_tracebuf_size","_uint32_t_flags"}},
		{493,	"grab_pgo_data",
	{"user_addr_t_uuid","_int_flags","_user_addr_t_buffer","_user_ssize_t_size"}},
		{494,	"persona",
	{"uint32_t_operation","_uint32_t_flags","_struct_kpersona_info_*info","_uid_t_*id","_size_t_*idlen"}},
		{499,	"work_interval_ctl",
	{"uint32_t_operation","_uint64_t_work_interval_id","_void_*arg","_size_t_len"}},
		{500,	"getentropy",
	{"void_*buffer","_size_t_size"}},
		{501,	"necp_open",
	{"int_flags"}},
		{502,	"necp_client_action",
	{"int_necp_fd","_uint32_t_action","_uuid_t_client_id","_size_t_client_id_len","_uint8_t_*buffer","_size_t_buffer_size"}},
		{515,	"ulock_wait",
	{"uint32_t_operation","_void_*addr","_uint64_t_value","_uint32_t_timeout"}},
		{516,	"ulock_wake",
	{"uint32_t_operation","_void_*addr","_uint64_t_wake_value"}},
		{517,	"fclonefileat",
	{"int_src_fd","_int_dst_dirfd","_user_addr_t_dst","_uint32_t_flags"}},
		{518,	"fs_snapshot",
	{"uint32_t_op","_int_dirfd","_user_addr_t_name1","_user_addr_t_name2","_user_addr_t_data","_uint32_t_flags"}},
		{520,	"terminate_with_payload",
	{"int_pid","_uint32_t_reason_namespace","_uint64_t_reason_code","_void_*payload","_uint32_t_payload_size","_const_char_*reason_string","_uint64_t_reason_flags"}},
		{521,	"abort_with_payload",
	{"uint32_t_reason_namespace","_uint64_t_reason_code","_void_*payload","_uint32_t_payload_size","_const_char_*reason_string","_uint64_t_reason_flags"}},
		{522,	"necp_session_open",
	{"int_flags"}},
		{523,	"necp_session_action",
	{"int_necp_fd","_uint32_t_action","_uint8_t_*in_buffer","_size_t_in_buffer_length","_uint8_t_*out_buffer","_size_t_out_buffer_length"}},
		{524,	"setattrlistat",
	{"int_fd","_const_char_*path","_struct_attrlist_*alist","_void_*attributeBuffer","_size_t_bufferSize","_uint32_t_options"}},
		{525,	"net_qos_guideline",
	{"struct_net_qos_param_*param","_uint32_t_param_len"}},
		{526,	"fmount",
	{"const_char_*type","_int_fd","_int_flags","_void_*data"}},
		{527,	"ntp_adjtime",
	{"struct_timex_*tp"}},
		{528,	"ntp_gettime",
	{"struct_ntptimeval_*ntvp"}},
		{529,	"os_fault_with_payload",
	{"uint32_t_reason_namespace","_uint64_t_reason_code","_void_*payload","_uint32_t_payload_size","_const_char_*reason_string","_uint64_t_reason_flags"}},
		{530,	"kqueue_workloop_ctl",
	{"user_addr_t_cmd","_uint64_t_options","_user_addr_t_addr","_size_t_sz"}},
		{531,	"mach_bridge_remote_time",
	{"uint64_t_local_timestamp"}}
	};
	const uint64_t bsc_size = sizeof(bsd_syscall_table)/sizeof(struct syscall_entry);
}
