#include "loader.hpp"
namespace LoadData
{
    //codes designed for divide large log file for parsing
    const std::map<std::string, uint64_t> op_code_map = {
        std::make_pair("ARGUS_IPC_kmsg_free", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_trap", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_link", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_recv", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_recv_voucher_r", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_send", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_boarder", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_thread_voucher", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_dump", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_dsc", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_msg_idsc", MACH_IPC_MSG),
        std::make_pair("ARGUS_IPC_voucher_bank", MACH_IPC_VOUCHER_INFO),
        std::make_pair("ARGUS_MKRUNNABLE", MACH_MK_RUN),
        std::make_pair("ARGUS_WAKEUP_REASON", MACH_MK_RUN),
        std::make_pair("ARGUS_WAIT", MACH_WAIT),
        std::make_pair("ARGUS_WAIT_REASON", MACH_WAIT),
        std::make_pair("ARGUS_Interrupt", INTR),
        std::make_pair("ARGUS_TS_MAINTENANCE", MACH_TS),
        std::make_pair("ARGUS_dispatch_enqueue", DISP_ENQ),
        std::make_pair("ARGUS_dispatch_execute", DISP_EXE),
        std::make_pair("ARGUS_dispatch_mig_server", DISP_MIG),
        std::make_pair("ARGUS_CALLCREATE", MACH_CALLCREATE),
        std::make_pair("ARGUS_CALLOUT", MACH_CALLOUT),
        std::make_pair("ARGUS_CALLCANCEL", MACH_CALLCANCEL),
        std::make_pair("ARGUS_DBG_BT", BACKTRACE),
        std::make_pair("ARGUS_HWBR_trap", BREAKPOINT_TRAP),
        std::make_pair("MACH_SYSCALL", MACH_SYS),
        std::make_pair("BSD_SYSCALL", BSD_SYS),
        std::make_pair("ARGUS_AppKit_SetNSView", CA_SET),
        std::make_pair("ARGUS_AppKit_GetEvent", NSAPPEVENT),
        std::make_pair("ARGUS_AppKit_SendEvent", NSAPPEVENT),
		std::make_pair("ARGUS_AppKit_CurrentEvent", NSAPPEVENT),
        std::make_pair("ARGUS_RL_DoEvents", RL_BOUNDARY),
        std::make_pair("ARGUS_RL_DoSource0", RL_BOUNDARY),
        std::make_pair("ARGUS_RL_DoSource1", RL_BOUNDARY),
        std::make_pair("ARGUS_RL_DoBlocks", RL_BOUNDARY),
        std::make_pair("ARGUS_RL_DoObserver", RL_BOUNDARY),
    };
}
